/* Automatically generated by './generator/entry.js' */
import { App, install as installCompnents } from '@ss/mtd-adapter'

import Icon from '@components/icon'
import ConfigProvider from '@components/config-provider'
import Tag from '@components/tag'
import Button from '@components/button'
import Switch from '@components/switch'
import Breadcrumb from '@components/breadcrumb'
import BreadcrumbItem from '@components/breadcrumb-item'
import BreadcrumbItemGroup from '@components/breadcrumb-item-group'
import Badge from '@components/badge'
import Popover from '@components/popover'
import Teleport from '@components/teleport'
import Tooltip from '@components/tooltip'
import RadioGroup from '@components/radio-group'
import RadioButton from '@components/radio-button'
import Radio from '@components/radio'
import Checkbox from '@components/checkbox'
import CheckboxGroup from '@components/checkbox-group'
import Input from '@components/input'
import Textarea from '@components/textarea'
import InputGroup from '@components/input-group'
import IconButton from '@components/icon-button'
import ButtonGroup from '@components/button-group'
import Select from '@components/select'
import Multiple from '@components/multiple'
import Dropdown from '@components/dropdown'
import DropdownMenu from '@components/dropdown-menu'
import DropdownMenuItem from '@components/dropdown-menu-item'
import Picker from '@components/picker'
import Option from '@components/option'
import Virtual from '@components/virtual'
import Menu from '@components/menu'
import MenuItem from '@components/menu-item'
import Submenu from '@components/submenu'
import Row from '@components/row'
import Col from '@components/col'
import InputSearch from '@components/input-search'
import InputNumber from '@components/input-number'
import Autocomplete from '@components/autocomplete'
import OptionGroup from '@components/option-group'
import Cascader from '@components/cascader'
import SelectInput from '@components/select-input'
import CascaderPanel from '@components/cascader-panel'
import Loading from '@components/loading'
import Tree from '@components/tree'
import TreeNode from '@components/tree-node'
import TreeSelect from '@components/tree-select'
import TimePicker from '@components/time-picker'
import DatePicker from '@components/date-picker'
import Spinner from '@components/spinner'
import Tabs from '@components/tabs'
import Table from '@components/table'
import TableColumn from '@components/table-column'
import Card from '@components/card'
import Notification from '@components/notification'
import Drawer from '@components/drawer'
import Slider from '@components/slider'
import Modal from '@components/modal'
import Message from '@components/message'
import Transitions from '@components/transitions'
import Progress from '@components/progress'
import Collapse from '@components/collapse'
import CollapseItem from '@components/collapse-item'
import List from '@components/list'
import ListItem from '@components/list-item'
import ListItemGroup from '@components/list-item-group'
import Contextmenu from '@components/contextmenu'
import DropdownMenuItemGroup from '@components/dropdown-menu-item-group'
import Skeleton from '@components/skeleton'
import Form from '@components/form'
import FormItem from '@components/form-item'
import Carousel from '@components/carousel'
import CarouselItem from '@components/carousel-item'
import Steps from '@components/steps'
import Step from '@components/step'
import Timeline from '@components/timeline'
import TimelineItem from '@components/timeline-item'
import Rate from '@components/rate'
import Transfer from '@components/transfer'
import TransferPanel from '@components/transfer-panel'
import TabPane from '@components/tab-pane'
import TabDrop from '@components/tab-drop'
import Announcement from '@components/announcement'
import Pagination from '@components/pagination'
import Affix from '@components/affix'
import Anchor from '@components/anchor'
import AnchorLink from '@components/anchor-link'
import Container from '@components/container'
import Header from '@components/header'
import Footer from '@components/footer'
import Aside from '@components/aside'
import Main from '@components/main'
import Popconfirm from '@components/popconfirm'
import File from '@components/file'
import Upload from '@components/upload'
import Confirm from '@components/confirm'
import Sidebar from '@components/sidebar'
import { config } from '@components/config-provider'

const components: any[] = [ // eslint-disable-line
  Icon,
  ConfigProvider,
  Tag,
  Button,
  Switch,
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbItemGroup,
  Badge,
  Popover,
  Teleport,
  Tooltip,
  RadioGroup,
  RadioButton,
  Radio,
  Checkbox,
  CheckboxGroup,
  Input,
  Textarea,
  InputGroup,
  IconButton,
  ButtonGroup,
  Select,
  Multiple,
  Dropdown,
  DropdownMenu,
  DropdownMenuItem,
  Picker,
  Option,
  Virtual,
  Menu,
  MenuItem,
  Submenu,
  Row,
  Col,
  InputSearch,
  InputNumber,
  Autocomplete,
  OptionGroup,
  Cascader,
  SelectInput,
  CascaderPanel,
  Loading,
  Tree,
  TreeNode,
  TreeSelect,
  TimePicker,
  DatePicker,
  Spinner,
  Tabs,
  Table,
  TableColumn,
  Card,
  Drawer,
  Slider,
  Modal,
  Transitions,
  Progress,
  Collapse,
  CollapseItem,
  List,
  ListItem,
  ListItemGroup,
  Contextmenu,
  DropdownMenuItemGroup,
  Skeleton,
  Form,
  FormItem,
  Carousel,
  CarouselItem,
  Steps,
  Step,
  Timeline,
  TimelineItem,
  Rate,
  Transfer,
  TransferPanel,
  TabPane,
  TabDrop,
  Announcement,
  Pagination,
  Affix,
  Anchor,
  AnchorLink,
  Container,
  Header,
  Footer,
  Aside,
  Main,
  Popconfirm,
  File,
  Upload,
  Sidebar,
]

const $mtd = {
  confirm: Confirm,
  notify: Notification,
  message: Message,
}

export function install(app: App) {
  installCompnents(app as any, components, $mtd)
}

export {
  Icon,
  ConfigProvider,
  Tag,
  Button,
  Switch,
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbItemGroup,
  Badge,
  Popover,
  Teleport,
  Tooltip,
  RadioGroup,
  RadioButton,
  Radio,
  Checkbox,
  CheckboxGroup,
  Input,
  Textarea,
  InputGroup,
  IconButton,
  ButtonGroup,
  Select,
  Multiple,
  Dropdown,
  DropdownMenu,
  DropdownMenuItem,
  Picker,
  Option,
  Virtual,
  Menu,
  MenuItem,
  Submenu,
  Row,
  Col,
  InputSearch,
  InputNumber,
  Autocomplete,
  OptionGroup,
  Cascader,
  SelectInput,
  CascaderPanel,
  Loading,
  Tree,
  TreeNode,
  TreeSelect,
  TimePicker,
  DatePicker,
  Spinner,
  Tabs,
  Table,
  TableColumn,
  Card,
  Notification,
  Drawer,
  Slider,
  Modal,
  Message,
  Transitions,
  Progress,
  Collapse,
  CollapseItem,
  List,
  ListItem,
  ListItemGroup,
  Contextmenu,
  DropdownMenuItemGroup,
  Skeleton,
  Form,
  FormItem,
  Carousel,
  CarouselItem,
  Steps,
  Step,
  Timeline,
  TimelineItem,
  Rate,
  Transfer,
  TransferPanel,
  TabPane,
  TabDrop,
  Announcement,
  Pagination,
  Affix,
  Anchor,
  AnchorLink,
  Container,
  Header,
  Footer,
  Aside,
  Main,
  Popconfirm,
  File,
  Upload,
  Confirm,
  Sidebar,
}

export default {
  version: '1.2.3-alpha.8',
  install,
  config,
}
